# Generated by Django 6.0.1 on 2026-02-06 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='condition',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='alert',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='dispatch_channels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='alert',
            name='email_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='alert',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='slack_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='alert',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alert',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='notification.alertrule'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(db_index=True, default='warning', max_length=20),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificationchannel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificationhistory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
