# Generated by Django 6.0.1 on 2026-02-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alert_condition_alert_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='event_start_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
