# Generated by Django 6.0.1 on 2026-02-06 09:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('overview', 'Overview'), ('infrastructure', 'Infrastructure'), ('application', 'Application'), ('security', 'Security'), ('performance', 'Performance'), ('custom', 'Custom')], db_index=True, max_length=50)),
                ('thumbnail', models.URLField(blank=True)),
                ('layout', models.JSONField(default=dict)),
                ('widgets', models.JSONField(default=list)),
                ('variables', models.JSONField(blank=True, default=list)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('is_official', models.BooleanField(default=False)),
                ('downloads', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard Template',
                'verbose_name_plural': 'Dashboard Templates',
            },
        ),
        migrations.CreateModel(
            name='FeaturedTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('promo_banner', models.URLField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='featured', to='template_dashboards.dashboardtemplate')),
            ],
            options={
                'verbose_name': 'Featured Template',
                'verbose_name_plural': 'Featured Templates',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TemplateInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('variable_values', models.JSONField(blank=True, default=dict)),
                ('customizations', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='template_dashboards.dashboardtemplate')),
            ],
            options={
                'verbose_name': 'Template Instance',
                'verbose_name_plural': 'Template Instances',
            },
        ),
        migrations.CreateModel(
            name='VariableCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('variable_type', models.CharField(max_length=50)),
                ('definition', models.JSONField(default=dict)),
                ('is_global', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Variable Catalog',
                'verbose_name_plural': 'Variable Catalogs',
            },
        ),
    ]
