# Generated by Django 6.0.1 on 2026-02-06 16:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securitymetrics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='securitymetric',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ComplianceFramework',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('version', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('controls', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compliance Framework',
                'verbose_name_plural': 'Compliance Frameworks',
            },
        ),
        migrations.CreateModel(
            name='SecurityIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('incident_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('contained', 'Contained'), ('remediated', 'Remediated'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='open', max_length=50)),
                ('category', models.CharField(choices=[('data_breach', 'Data Breach'), ('malware', 'Malware'), ('phishing', 'Phishing'), ('unauthorized_access', 'Unauthorized Access'), ('dos', 'Denial of Service'), ('insider_threat', 'Insider Threat'), ('other', 'Other')], db_index=True, max_length=100)),
                ('affected_systems', models.JSONField(default=list)),
                ('affected_users', models.JSONField(default=list)),
                ('timeline', models.JSONField(default=list)),
                ('detected_at', models.DateTimeField()),
                ('contained_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.CharField(blank=True, max_length=255)),
                ('team', models.CharField(blank=True, max_length=100)),
                ('root_cause', models.TextField(blank=True)),
                ('lessons_learned', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Incident',
                'verbose_name_plural': 'Security Incidents',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('rules', models.JSONField(default=list)),
                ('is_enabled', models.BooleanField(default=True)),
                ('enforcement_mode', models.CharField(choices=[('monitor', 'Monitor Only'), ('warn', 'Warn'), ('enforce', 'Enforce')], default='monitor', max_length=20)),
                ('applies_to', models.JSONField(default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Policy',
                'verbose_name_plural': 'Security Policies',
            },
        ),
        migrations.CreateModel(
            name='ComplianceCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('control_id', models.CharField(db_index=True, max_length=50)),
                ('control_name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'N/A'), ('pending', 'Pending'), ('manual', 'Manual Review')], default='pending', max_length=20)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('last_checked', models.DateTimeField()),
                ('next_check', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='securitymetrics.complianceframework')),
            ],
            options={
                'verbose_name': 'Compliance Check',
                'verbose_name_plural': 'Compliance Checks',
                'unique_together': {('framework', 'control_id')},
            },
        ),
        migrations.CreateModel(
            name='VulnerabilityScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('host', models.CharField(db_index=True, max_length=255)),
                ('scan_type', models.CharField(choices=[('container', 'Container'), ('host', 'Host'), ('dependency', 'Dependency'), ('infrastructure', 'Infrastructure')], default='host', max_length=50)),
                ('cve_id', models.CharField(db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('unknown', 'Unknown')], db_index=True, max_length=20)),
                ('cvss_score', models.FloatField(blank=True, null=True)),
                ('cvss_vector', models.CharField(blank=True, max_length=100)),
                ('package_name', models.CharField(max_length=255)),
                ('package_version', models.CharField(max_length=100)),
                ('fixed_version', models.CharField(blank=True, max_length=100)),
                ('remediation_status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('accepted', 'Risk Accepted'), ('false_positive', 'False Positive')], default='open', max_length=50)),
                ('remediation_notes', models.TextField(blank=True)),
                ('first_detected', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vulnerability Scan',
                'verbose_name_plural': 'Vulnerability Scans',
                'indexes': [models.Index(fields=['host', 'cve_id'], name='securitymet_host_f23248_idx'), models.Index(fields=['severity', 'remediation_status'], name='securitymet_severit_9667d5_idx')],
            },
        ),
    ]
