# Generated by Django 6.0.1 on 2026-02-06 09:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('trace_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('service_name', models.CharField(db_index=True, max_length=255)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('error', 'Error'), ('unset', 'Unset')], default='unset', max_length=20)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trace',
                'verbose_name_plural': 'Traces',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(db_index=True, max_length=255)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('data', models.JSONField(default=dict)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'indexes': [models.Index(fields=['name', 'timestamp'], name='core_event_name_53eb9a_idx'), models.Index(fields=['event_type', 'timestamp'], name='core_event_event_t_996a6f_idx')],
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(db_index=True, max_length=255)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], db_index=True, max_length=20)),
                ('message', models.TextField()),
                ('logger_name', models.CharField(blank=True, max_length=255)),
                ('trace_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('span_id', models.CharField(blank=True, max_length=32)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log Entry',
                'verbose_name_plural': 'Log Entries',
                'indexes': [models.Index(fields=['level', 'timestamp'], name='core_logent_level_dc1a55_idx'), models.Index(fields=['source', 'level'], name='core_logent_source_72625e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(db_index=True, max_length=255)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('metric_type', models.CharField(choices=[('counter', 'Counter'), ('gauge', 'Gauge'), ('histogram', 'Histogram'), ('summary', 'Summary')], default='gauge', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Metric',
                'verbose_name_plural': 'Metrics',
                'indexes': [models.Index(fields=['name', 'timestamp'], name='core_metric_name_a0bb32_idx'), models.Index(fields=['source', 'timestamp'], name='core_metric_source_ab465f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Span',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('span_id', models.CharField(db_index=True, max_length=32)),
                ('parent_span_id', models.CharField(blank=True, max_length=32, null=True)),
                ('name', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(default='unset', max_length=20)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('trace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spans', to='core.trace')),
            ],
            options={
                'verbose_name': 'Span',
                'verbose_name_plural': 'Spans',
                'unique_together': {('trace', 'span_id')},
            },
        ),
    ]
