# Generated by Django 6.0.1 on 2026-02-06 09:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiskMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(db_index=True, max_length=255)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('host', models.CharField(db_index=True, max_length=255)),
                ('mount_point', models.CharField(db_index=True, max_length=255)),
                ('device', models.CharField(max_length=255)),
                ('total_bytes', models.BigIntegerField(default=0)),
                ('used_bytes', models.BigIntegerField(default=0)),
                ('free_bytes', models.BigIntegerField(default=0)),
                ('usage_percent', models.FloatField(default=0.0)),
                ('read_bytes', models.BigIntegerField(default=0)),
                ('write_bytes', models.BigIntegerField(default=0)),
                ('read_count', models.BigIntegerField(default=0)),
                ('write_count', models.BigIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Disk Metric',
                'verbose_name_plural': 'Disk Metrics',
            },
        ),
        migrations.CreateModel(
            name='ProcessMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(db_index=True, max_length=255)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('host', models.CharField(db_index=True, max_length=255)),
                ('pid', models.IntegerField()),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('cpu_percent', models.FloatField(default=0.0)),
                ('memory_percent', models.FloatField(default=0.0)),
                ('memory_rss_bytes', models.BigIntegerField(default=0)),
                ('threads', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Process Metric',
                'verbose_name_plural': 'Process Metrics',
            },
        ),
        migrations.CreateModel(
            name='SystemMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(db_index=True, max_length=255)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('host', models.CharField(db_index=True, max_length=255)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('cpu_percent', models.FloatField(default=0.0)),
                ('cpu_count', models.IntegerField(default=0)),
                ('load_avg_1min', models.FloatField(default=0.0)),
                ('load_avg_5min', models.FloatField(default=0.0)),
                ('load_avg_15min', models.FloatField(default=0.0)),
                ('memory_total_bytes', models.BigIntegerField(default=0)),
                ('memory_available_bytes', models.BigIntegerField(default=0)),
                ('memory_used_bytes', models.BigIntegerField(default=0)),
                ('memory_percent', models.FloatField(default=0.0)),
                ('swap_total_bytes', models.BigIntegerField(default=0)),
                ('swap_used_bytes', models.BigIntegerField(default=0)),
                ('swap_percent', models.FloatField(default=0.0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Metric',
                'verbose_name_plural': 'System Metrics',
                'indexes': [models.Index(fields=['host', 'timestamp'], name='systemmetri_host_c12037_idx')],
            },
        ),
    ]
