# Generated by Django 6.0.1 on 2026-02-06 16:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemmetrics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='diskmetric',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='processmetric',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='systemmetric',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ContainerMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(db_index=True, max_length=255)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('host', models.CharField(db_index=True, max_length=255)),
                ('container_id', models.CharField(db_index=True, max_length=64)),
                ('container_name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=500)),
                ('namespace', models.CharField(blank=True, max_length=255)),
                ('pod_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped'), ('paused', 'Paused'), ('restarting', 'Restarting'), ('created', 'Created'), ('exited', 'Exited')], default='running', max_length=50)),
                ('cpu_percent', models.FloatField(default=0.0)),
                ('cpu_limit_cores', models.FloatField(blank=True, null=True)),
                ('cpu_request_cores', models.FloatField(blank=True, null=True)),
                ('memory_usage_bytes', models.BigIntegerField(default=0)),
                ('memory_limit_bytes', models.BigIntegerField(default=0)),
                ('memory_request_bytes', models.BigIntegerField(blank=True, null=True)),
                ('memory_percent', models.FloatField(default=0.0)),
                ('network_rx_bytes', models.BigIntegerField(default=0)),
                ('network_tx_bytes', models.BigIntegerField(default=0)),
                ('restart_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Container Metric',
                'verbose_name_plural': 'Container Metrics',
                'indexes': [models.Index(fields=['host', 'container_id', 'timestamp'], name='systemmetri_host_573b80_idx'), models.Index(fields=['namespace', 'pod_name', 'timestamp'], name='systemmetri_namespa_e89759_idx')],
            },
        ),
        migrations.CreateModel(
            name='GPUMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(db_index=True, max_length=255)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('host', models.CharField(db_index=True, max_length=255)),
                ('gpu_index', models.IntegerField()),
                ('gpu_uuid', models.CharField(blank=True, max_length=64)),
                ('gpu_name', models.CharField(max_length=255)),
                ('utilization_percent', models.FloatField(default=0.0)),
                ('memory_utilization_percent', models.FloatField(default=0.0)),
                ('memory_used_mb', models.IntegerField(default=0)),
                ('memory_total_mb', models.IntegerField(default=0)),
                ('memory_free_mb', models.IntegerField(default=0)),
                ('temperature_celsius', models.FloatField(default=0.0)),
                ('power_watts', models.FloatField(default=0.0)),
                ('power_limit_watts', models.FloatField(blank=True, null=True)),
                ('running_processes', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GPU Metric',
                'verbose_name_plural': 'GPU Metrics',
                'indexes': [models.Index(fields=['host', 'gpu_index', 'timestamp'], name='systemmetri_host_d8969f_idx')],
            },
        ),
        migrations.CreateModel(
            name='KubernetesEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cluster', models.CharField(db_index=True, max_length=255)),
                ('namespace', models.CharField(db_index=True, max_length=255)),
                ('kind', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('uid', models.CharField(blank=True, max_length=64)),
                ('event_type', models.CharField(choices=[('Normal', 'Normal'), ('Warning', 'Warning')], default='Normal', max_length=50)),
                ('reason', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('first_timestamp', models.DateTimeField(blank=True, null=True)),
                ('last_timestamp', models.DateTimeField(blank=True, null=True)),
                ('count', models.IntegerField(default=1)),
                ('source_component', models.CharField(blank=True, max_length=100)),
                ('source_host', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kubernetes Event',
                'verbose_name_plural': 'Kubernetes Events',
                'indexes': [models.Index(fields=['cluster', 'namespace', 'kind'], name='systemmetri_cluster_dc0054_idx')],
            },
        ),
        migrations.CreateModel(
            name='KubernetesPod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cluster', models.CharField(db_index=True, max_length=255)),
                ('namespace', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('uid', models.CharField(max_length=64, unique=True)),
                ('phase', models.CharField(choices=[('Pending', 'Pending'), ('Running', 'Running'), ('Succeeded', 'Succeeded'), ('Failed', 'Failed'), ('Unknown', 'Unknown')], default='Unknown', max_length=50)),
                ('node_name', models.CharField(blank=True, max_length=255)),
                ('host_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('pod_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('annotations', models.JSONField(blank=True, default=dict)),
                ('container_count', models.IntegerField(default=0)),
                ('ready_containers', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kubernetes Pod',
                'verbose_name_plural': 'Kubernetes Pods',
                'unique_together': {('cluster', 'namespace', 'name')},
            },
        ),
    ]
