# Generated by Django 6.0.1 on 2026-02-06 09:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigWatcher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source_type', models.CharField(max_length=50)),
                ('source_name', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('change_type', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Config Watcher',
                'verbose_name_plural': 'Config Watchers',
            },
        ),
        migrations.CreateModel(
            name='ServiceRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('version', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('framework', models.CharField(max_length=100)),
                ('owner_team', models.CharField(blank=True, max_length=100)),
                ('repo_url', models.URLField(blank=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Registry',
                'verbose_name_plural': 'Service Registries',
            },
        ),
        migrations.CreateModel(
            name='DeploymentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.CharField(max_length=50)),
                ('environment', models.CharField(max_length=50)),
                ('status', models.CharField(default='in_progress', max_length=20)),
                ('triggered_by', models.CharField(max_length=100)),
                ('commit_hash', models.CharField(blank=True, max_length=100)),
                ('pipeline_url', models.URLField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='application.serviceregistry')),
            ],
            options={
                'verbose_name': 'Deployment Event',
                'verbose_name_plural': 'Deployment Events',
            },
        ),
        migrations.CreateModel(
            name='DependencyMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('dependency_type', models.CharField(default='http', max_length=50)),
                ('is_critical', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumes', to='application.serviceregistry')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provided_to', to='application.serviceregistry')),
            ],
            options={
                'verbose_name': 'Dependency Map',
                'verbose_name_plural': 'Dependency Maps',
                'unique_together': {('consumer', 'provider')},
            },
        ),
    ]
