# Generated by Django 6.0.1 on 2026-02-06 09:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(db_index=True, max_length=255)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('host', models.CharField(db_index=True, max_length=255)),
                ('active_connections', models.IntegerField(default=0)),
                ('established_connections', models.IntegerField(default=0)),
                ('time_wait_connections', models.IntegerField(default=0)),
                ('close_wait_connections', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Connection Metric',
                'verbose_name_plural': 'Connection Metrics',
            },
        ),
        migrations.CreateModel(
            name='NetworkMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(db_index=True, max_length=255)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('host', models.CharField(db_index=True, max_length=255)),
                ('interface', models.CharField(db_index=True, max_length=100)),
                ('bytes_sent', models.BigIntegerField(default=0)),
                ('bytes_received', models.BigIntegerField(default=0)),
                ('packets_sent', models.BigIntegerField(default=0)),
                ('packets_received', models.BigIntegerField(default=0)),
                ('errors_in', models.IntegerField(default=0)),
                ('errors_out', models.IntegerField(default=0)),
                ('drops_in', models.IntegerField(default=0)),
                ('drops_out', models.IntegerField(default=0)),
                ('latency_ms', models.FloatField(default=0.0)),
                ('jitter_ms', models.FloatField(default=0.0)),
                ('packet_loss_percent', models.FloatField(default=0.0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Network Metric',
                'verbose_name_plural': 'Network Metrics',
                'indexes': [models.Index(fields=['host', 'interface', 'timestamp'], name='netmetrics__host_52f3c1_idx')],
            },
        ),
    ]
