# Generated by Django 6.0.1 on 2026-02-06 16:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netmetrics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionmetric',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='networkmetric',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DNSMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(db_index=True, max_length=255)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('host', models.CharField(db_index=True, max_length=255)),
                ('query_domain', models.CharField(db_index=True, max_length=255)),
                ('query_type', models.CharField(choices=[('A', 'A'), ('AAAA', 'AAAA'), ('CNAME', 'CNAME'), ('MX', 'MX'), ('TXT', 'TXT'), ('NS', 'NS'), ('PTR', 'PTR'), ('SRV', 'SRV')], default='A', max_length=20)),
                ('response_time_ms', models.FloatField()),
                ('resolver', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('success', 'Success'), ('nxdomain', 'NXDOMAIN'), ('servfail', 'SERVFAIL'), ('timeout', 'Timeout'), ('refused', 'Refused')], default='success', max_length=20)),
                ('response_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('ttl_seconds', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DNS Metric',
                'verbose_name_plural': 'DNS Metrics',
            },
        ),
        migrations.CreateModel(
            name='ServiceDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_service', models.CharField(db_index=True, max_length=255)),
                ('source_namespace', models.CharField(blank=True, max_length=255)),
                ('target_service', models.CharField(db_index=True, max_length=255)),
                ('target_namespace', models.CharField(blank=True, max_length=255)),
                ('dependency_type', models.CharField(choices=[('http', 'HTTP'), ('grpc', 'gRPC'), ('tcp', 'TCP'), ('database', 'Database'), ('cache', 'Cache'), ('queue', 'Message Queue')], default='http', max_length=50)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('avg_latency_ms', models.FloatField(default=0.0)),
                ('error_rate', models.FloatField(default=0.0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Dependency',
                'verbose_name_plural': 'Service Dependencies',
                'unique_together': {('source_service', 'target_service', 'dependency_type')},
            },
        ),
        migrations.CreateModel(
            name='ServiceMeshMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(db_index=True, max_length=255)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('source_service', models.CharField(db_index=True, max_length=255)),
                ('source_namespace', models.CharField(db_index=True, max_length=255)),
                ('source_version', models.CharField(blank=True, max_length=100)),
                ('destination_service', models.CharField(db_index=True, max_length=255)),
                ('destination_namespace', models.CharField(db_index=True, max_length=255)),
                ('destination_version', models.CharField(blank=True, max_length=100)),
                ('request_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('latency_p50_ms', models.FloatField(default=0.0)),
                ('latency_p90_ms', models.FloatField(default=0.0)),
                ('latency_p95_ms', models.FloatField(default=0.0)),
                ('latency_p99_ms', models.FloatField(default=0.0)),
                ('retries', models.IntegerField(default=0)),
                ('timeouts', models.IntegerField(default=0)),
                ('circuit_breaker_open', models.BooleanField(default=False)),
                ('connection_pool_exhausted', models.IntegerField(default=0)),
                ('protocol', models.CharField(default='http', max_length=20)),
                ('response_flags', models.CharField(blank=True, max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Mesh Metric',
                'verbose_name_plural': 'Service Mesh Metrics',
                'indexes': [models.Index(fields=['source_service', 'destination_service', 'timestamp'], name='netmetrics__source__9f3eec_idx'), models.Index(fields=['source_namespace', 'destination_namespace'], name='netmetrics__source__64edb0_idx')],
            },
        ),
        migrations.CreateModel(
            name='TLSCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('host', models.CharField(db_index=True, max_length=255)),
                ('port', models.IntegerField(default=443)),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('issuer', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=100)),
                ('not_before', models.DateTimeField()),
                ('not_after', models.DateTimeField()),
                ('days_until_expiry', models.IntegerField()),
                ('fingerprint_sha256', models.CharField(max_length=64)),
                ('signature_algorithm', models.CharField(max_length=50)),
                ('key_size', models.IntegerField()),
                ('is_valid', models.BooleanField(default=True)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('chain_length', models.IntegerField(default=0)),
                ('chain_valid', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TLS Certificate',
                'verbose_name_plural': 'TLS Certificates',
                'unique_together': {('host', 'port', 'domain')},
            },
        ),
    ]
