apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    istio-injection: {{ .Values.istio.injection }}
---
{{- if .Values.istio.enabled }}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: {{ .Values.namespace }}
spec:
  mtls:
    mode: {{ .Values.istio.mtls }}
{{- end }}
