apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "observer-eye.fullname" . }}-db
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "observer-eye.name" . }}-db
  template:
    metadata:
      labels:
        app: {{ include "observer-eye.name" . }}-db
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        envFrom:
        - configMapRef:
            name: {{ include "observer-eye.fullname" . }}-config
        - secretRef:
            name: {{ include "observer-eye.fullname" . }}-secrets
        env:
        - name: POSTGRES_DB
          value: {{ .Values.config.dbName | quote }}
        - name: POSTGRES_USER
          value: {{ .Values.config.dbUser | quote }}
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: {{ include "observer-eye.fullname" . }}-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ include "observer-eye.name" . }}-db
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "observer-eye.fullname" . }}-postgres-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.postgres.size }}
