apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "observer-eye.fullname" . }}-frontend
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "observer-eye.name" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ include "observer-eye.name" . }}-frontend
    spec:
      containers:
      - name: frontend
        image: {{ .Values.images.frontend }}
        imagePullPolicy: {{ .Values.images.pullPolicy }}
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ include "observer-eye.name" . }}-frontend
  ports:
  - port: 80
    targetPort: 80
