apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "observer-eye.fullname" . }}-backend-hpa
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "observer-eye.fullname" . }}-backend
  minReplicas: {{ .Values.scaling.backend.minReplicas | default 2 }}
  maxReplicas: {{ .Values.scaling.backend.maxReplicas | default 10 }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
