apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "observer-eye.fullname" . }}-zookeeper
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "observer-eye.name" . }}-zookeeper
  template:
    metadata:
      labels:
        app: {{ include "observer-eye.name" . }}-zookeeper
    spec:
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:7.4.0
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
        ports:
        - containerPort: 2181
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ include "observer-eye.name" . }}-zookeeper
  ports:
  - port: 2181
    targetPort: 2181
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "observer-eye.fullname" . }}-kafka
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "observer-eye.name" . }}-kafka
  template:
    metadata:
      labels:
        app: {{ include "observer-eye.name" . }}-kafka
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:7.4.0
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper-service:2181"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka-service:9092"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "PLAINTEXT:PLAINTEXT"
        ports:
        - containerPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ include "observer-eye.name" . }}-kafka
  ports:
  - port: 9092
    targetPort: 9092
