# Generated by Django 6.0.1 on 2026-02-06 09:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('actor', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=255)),
                ('changes', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Trail',
                'verbose_name_plural': 'Audit Trails',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CompliancePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('framework', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(default='active', max_length=20)),
                ('last_check_status', models.CharField(default='unknown', max_length=20)),
                ('last_check_time', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compliance Policy',
                'verbose_name_plural': 'Compliance Policies',
            },
        ),
        migrations.CreateModel(
            name='ThreatEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('threat_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('detected', 'Detected'), ('blocked', 'Blocked'), ('mitigated', 'Mitigated')], default='detected', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_threatevent_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Threat Event',
                'verbose_name_plural': 'Threat Events',
            },
        ),
        migrations.CreateModel(
            name='VulnerabilityScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('target', models.CharField(max_length=255)),
                ('scan_tpe', models.CharField(default='static', max_length=50)),
                ('scanner_name', models.CharField(max_length=100)),
                ('cve_id', models.CharField(db_index=True, max_length=50)),
                ('severity', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(default='open', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vulnerability Scan',
                'verbose_name_plural': 'Vulnerability Scans',
            },
        ),
    ]
