# Generated by Django 6.0.1 on 2026-02-06 09:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadBalancerStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('lb_name', models.CharField(db_index=True, max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('active_connections', models.IntegerField(default=0)),
                ('requests_per_second', models.FloatField(default=0.0)),
                ('bytes_in', models.BigIntegerField(default=0)),
                ('bytes_out', models.BigIntegerField(default=0)),
                ('p99_latency_ms', models.FloatField(default=0.0)),
                ('status_code_5xx', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Load Balancer Stats',
                'verbose_name_plural': 'Load Balancer Stats',
            },
        ),
        migrations.CreateModel(
            name='TrafficStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('ingress_bytes', models.BigIntegerField(default=0)),
                ('egress_bytes', models.BigIntegerField(default=0)),
                ('total_requests', models.IntegerField(default=0)),
                ('region', models.CharField(default='global', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Traffic Stats',
                'verbose_name_plural': 'Traffic Stats',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RouteAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('route_path', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('avg_latency_ms', models.FloatField(default=0.0)),
                ('p95_latency_ms', models.FloatField(default=0.0)),
                ('p99_latency_ms', models.FloatField(default=0.0)),
                ('error_count', models.IntegerField(default=0)),
                ('call_count', models.IntegerField(default=0)),
                ('service', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Route Analytics',
                'verbose_name_plural': 'Route Analytics',
                'unique_together': {('route_path', 'method', 'service')},
            },
        ),
    ]
