# Generated by Django 6.0.1 on 2026-02-06 09:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FirewallRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('action', models.CharField(default='allow', max_length=20)),
                ('source_cidr', models.CharField(default='0.0.0.0/0', max_length=50)),
                ('destination_cidr', models.CharField(default='0.0.0.0/0', max_length=50)),
                ('port_range', models.CharField(default='any', max_length=50)),
                ('protocol', models.CharField(default='any', max_length=20)),
                ('priority', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Firewall Rule',
                'verbose_name_plural': 'Firewall Rules',
            },
        ),
        migrations.CreateModel(
            name='TrafficFlow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source_ip', models.GenericIPAddressField()),
                ('destination_ip', models.GenericIPAddressField()),
                ('source_port', models.IntegerField()),
                ('destination_port', models.IntegerField()),
                ('protocol', models.CharField(max_length=10)),
                ('bytes_transferred', models.BigIntegerField(default=0)),
                ('packets_transferred', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Traffic Flow',
                'verbose_name_plural': 'Traffic Flows',
            },
        ),
        migrations.CreateModel(
            name='VPNConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('connection_id', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(default='site-to-site', max_length=50)),
                ('remote_gateway', models.GenericIPAddressField(null=True)),
                ('tunnel_status', models.CharField(default='down', max_length=20)),
                ('bandwidth_mbps', models.FloatField(default=0.0)),
                ('connected_check_time', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'VPN Connection',
                'verbose_name_plural': 'VPN Connections',
            },
        ),
        migrations.CreateModel(
            name='NetworkInterface',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('hostname', models.CharField(db_index=True, max_length=255)),
                ('interface_name', models.CharField(max_length=50)),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('ipv4_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mtu', models.IntegerField(default=1500)),
                ('speed_mbps', models.IntegerField(default=1000)),
                ('status', models.CharField(default='up', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Network Interface',
                'verbose_name_plural': 'Network Interfaces',
                'unique_together': {('hostname', 'interface_name')},
            },
        ),
    ]
