# Generated by Django 6.0.1 on 2026-02-06 09:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(db_index=True, max_length=255)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('app_name', models.CharField(db_index=True, max_length=255)),
                ('environment', models.CharField(db_index=True, default='production', max_length=50)),
                ('request_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('avg_latency_ms', models.FloatField(default=0.0)),
                ('p50_latency_ms', models.FloatField(default=0.0)),
                ('p95_latency_ms', models.FloatField(default=0.0)),
                ('p99_latency_ms', models.FloatField(default=0.0)),
                ('requests_per_second', models.FloatField(default=0.0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application Metric',
                'verbose_name_plural': 'Application Metrics',
                'indexes': [models.Index(fields=['app_name', 'timestamp'], name='appmetrics__app_nam_7773b6_idx')],
            },
        ),
        migrations.CreateModel(
            name='EndpointMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(db_index=True, max_length=255)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('app_name', models.CharField(db_index=True, max_length=255)),
                ('endpoint', models.CharField(db_index=True, max_length=500)),
                ('method', models.CharField(max_length=10)),
                ('request_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('avg_latency_ms', models.FloatField(default=0.0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Endpoint Metric',
                'verbose_name_plural': 'Endpoint Metrics',
                'indexes': [models.Index(fields=['app_name', 'endpoint', 'timestamp'], name='appmetrics__app_nam_270c49_idx')],
            },
        ),
    ]
