# Generated by Django 6.0.1 on 2026-02-06 16:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_featureflag_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('total_metrics_limit', models.BigIntegerField(default=10000000)),
                ('total_logs_limit_gb', models.FloatField(default=100.0)),
                ('retention_days', models.IntegerField(default=30)),
                ('ai_enabled', models.BooleanField(default=True)),
                ('custom_dashboards_limit', models.IntegerField(default=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workspace Settings',
                'verbose_name_plural': 'Workspace Settings',
            },
        ),
    ]
