# Generated by Django 6.0.1 on 2026-02-06 09:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogPipeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('source_type', models.CharField(choices=[('file', 'File'), ('tcp', 'TCP'), ('udp', 'UDP'), ('syslog', 'Syslog')], default='tcp', max_length=50)),
                ('port', models.IntegerField(default=514)),
                ('parsers', models.JSONField(blank=True, default=list)),
                ('destination_type', models.CharField(choices=[('elasticsearch', 'Elasticsearch'), ('s3', 'S3 Bucket'), ('stdout', 'Console')], default='elasticsearch', max_length=50)),
                ('destination_config', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log Pipeline',
                'verbose_name_plural': 'Log Pipelines',
            },
        ),
        migrations.CreateModel(
            name='SanitizationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('pattern_type', models.CharField(choices=[('regex', 'Regex Pattern'), ('keyword', 'Exact Keyword')], default='regex', max_length=20)),
                ('pattern', models.CharField(max_length=500)),
                ('replacement', models.CharField(default='***REDACTED***', max_length=100)),
                ('is_global', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('apply_to_pipelines', models.ManyToManyField(blank=True, to='logstach.logpipeline')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sanitization Rule',
                'verbose_name_plural': 'Sanitization Rules',
            },
        ),
    ]
