# Generated by Django 6.0.1 on 2026-02-06 09:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.CharField(max_length=50)),
                ('resource_type', models.CharField(max_length=100)),
                ('resource_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=50)),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='active', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cloud Resource',
                'verbose_name_plural': 'Cloud Resources',
            },
        ),
        migrations.CreateModel(
            name='KubernetesCluster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('api_server_url', models.URLField()),
                ('version', models.CharField(max_length=50)),
                ('status', models.CharField(default='active', max_length=20)),
                ('region', models.CharField(blank=True, max_length=50)),
                ('provider', models.CharField(default='self-hosted', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kubernetes Cluster',
                'verbose_name_plural': 'Kubernetes Clusters',
            },
        ),
        migrations.CreateModel(
            name='SystemResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('hostname', models.CharField(max_length=255, unique=True)),
                ('os_name', models.CharField(max_length=100)),
                ('cpu_cores', models.IntegerField(default=1)),
                ('memory_gb', models.FloatField(default=1.0)),
                ('disk_gb', models.FloatField(default=10.0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('region', models.CharField(default='local', max_length=50)),
                ('environment', models.CharField(default='dev', max_length=50)),
                ('agent_version', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(default='offline', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Resource',
                'verbose_name_plural': 'System Resources',
            },
        ),
        migrations.CreateModel(
            name='KubernetesNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('node_role', models.CharField(default='worker', max_length=50)),
                ('status', models.CharField(default='Ready', max_length=20)),
                ('capacity_cpu', models.IntegerField(default=0)),
                ('capacity_memory', models.BigIntegerField(default=0)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='system.kubernetescluster')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('system_resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='k8s_node', to='system.systemresource')),
            ],
            options={
                'verbose_name': 'Kubernetes Node',
                'verbose_name_plural': 'Kubernetes Nodes',
            },
        ),
        migrations.CreateModel(
            name='KubernetesPod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('namespace', models.CharField(default='default', max_length=100)),
                ('phase', models.CharField(default='Pending', max_length=50)),
                ('restart_count', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pods', to='system.kubernetescluster')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pods', to='system.kubernetesnode')),
            ],
            options={
                'verbose_name': 'Kubernetes Pod',
                'verbose_name_plural': 'Kubernetes Pods',
                'unique_together': {('cluster', 'namespace', 'name')},
            },
        ),
    ]
