# Generated by Django 6.0.1 on 2026-02-06 09:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APMError',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(db_index=True, max_length=255)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('app_name', models.CharField(db_index=True, max_length=255)),
                ('error_type', models.CharField(db_index=True, max_length=255)),
                ('message', models.TextField()),
                ('stack_trace', models.TextField(blank=True)),
                ('transaction_name', models.CharField(blank=True, max_length=500)),
                ('trace_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('handled', models.BooleanField(default=True)),
                ('count', models.IntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'APM Error',
                'verbose_name_plural': 'APM Errors',
            },
        ),
        migrations.CreateModel(
            name='APMTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(db_index=True, max_length=255)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('app_name', models.CharField(db_index=True, max_length=255)),
                ('transaction_name', models.CharField(db_index=True, max_length=500)),
                ('transaction_type', models.CharField(default='request', max_length=100)),
                ('duration_ms', models.FloatField()),
                ('cpu_time_ms', models.FloatField(default=0.0)),
                ('result', models.CharField(default='success', max_length=50)),
                ('outcome', models.CharField(blank=True, max_length=50)),
                ('http_method', models.CharField(blank=True, max_length=10)),
                ('http_status_code', models.IntegerField(blank=True, null=True)),
                ('http_url', models.CharField(blank=True, max_length=2000)),
                ('trace_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('span_id', models.CharField(blank=True, max_length=32)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'APM Transaction',
                'verbose_name_plural': 'APM Transactions',
            },
        ),
        migrations.CreateModel(
            name='APMSpan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=500)),
                ('span_type', models.CharField(max_length=100)),
                ('duration_ms', models.FloatField()),
                ('start_offset_ms', models.FloatField(default=0.0)),
                ('db_type', models.CharField(blank=True, max_length=50)),
                ('db_statement', models.TextField(blank=True)),
                ('http_url', models.CharField(blank=True, max_length=2000)),
                ('http_status_code', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spans', to='application_performance_monitoring.apmtransaction')),
            ],
            options={
                'verbose_name': 'APM Span',
                'verbose_name_plural': 'APM Spans',
            },
        ),
        migrations.AddIndex(
            model_name='apmtransaction',
            index=models.Index(fields=['app_name', 'transaction_name', 'timestamp'], name='application_app_nam_556ff1_idx'),
        ),
    ]
